[workspace]
resolver = "2"
members = ["crates/sagrado-theme", "crates/sagrado-ui", "crates/sagrado-app", "crates/sagrado-textedit"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
thiserror = "2"
