//! Widget image slots of the appearance engine.
//!
//! Slot indices match the image table of Haxial `.hap` files (528 entries),
//! so imported appearances map 1:1 onto Sagrado widgets. Names follow the
//! AppearanceEdit documentation. Only the slots currently rendered by the
//! engine are listed; unknown slots are still imported and kept by index.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum Slot {
    PushButtonNormal = 25,
    PushButtonHilited = 26,
    PushButtonDisabled = 27,
    DefaultButtonNormal = 37,
    DefaultButtonHilited = 38,
    DefaultButtonDisabled = 39,
    TickBlankNormal = 57,
    TickBlankHilited = 58,
    TickBlankDisabled = 59,
    TickTickedNormal = 61,
    TickTickedHilited = 62,
    TickTickedDisabled = 63,
    MutexBlankNormal = 69,
    MutexBlankHilited = 70,
    MutexBlankDisabled = 71,
    MutexTickedNormal = 73,
    MutexTickedHilited = 74,
    MutexTickedDisabled = 75,
    HSliderBarNormal = 89,
    HSliderBarHilited = 90,
    HSliderBarDisabled = 91,
    HSliderIndicatorNormal = 93,
    HSliderIndicatorHilited = 94,
    HSliderIndicatorDisabled = 95,
    HorizSeparator = 105,
    VertSeparator = 106,
    Box = 107,
    FramedRaisedBox = 108,
    ProgressBar = 111,
    ProgressBarFill = 112,
    PopupButtonNormal = 130,
    PopupButtonHilited = 131,
    PopupButtonDisabled = 132,
    PopupArrowNormal = 134,
    PopupArrowHilited = 135,
    PopupArrowDisabled = 136,
    PopupSymbolNormal = 150,
    PopupSymbolHilited = 151,
    PopupSymbolDisabled = 152,
    HScrollDoubleArrows = 162,
    HScrollSingleArrows = 163,
    HScrollDisabled = 164,
    HScrollTrack = 165,
    HScrollThumbNormal = 166,
    HScrollThumbHilited = 167,
    HScrollGripNormal = 169,
    HScrollGripHilited = 170,
    HScrollLeftNormal = 172,
    HScrollRightNormal = 173,
    HScrollLeftHilited = 174,
    HScrollRightHilited = 175,
    HScrollLeftDisabled = 176,
    HScrollRightDisabled = 177,
    VScrollDoubleArrows = 181,
    VScrollSingleArrows = 182,
    VScrollDisabled = 183,
    VScrollTrack = 184,
    VScrollThumbNormal = 185,
    VScrollThumbHilited = 186,
    VScrollGripNormal = 188,
    VScrollGripHilited = 189,
    VScrollUpNormal = 191,
    VScrollDownNormal = 192,
    VScrollUpHilited = 193,
    VScrollDownHilited = 194,
    VScrollUpDisabled = 195,
    VScrollDownDisabled = 196,
    WindowTitleBarActive = 220,
    WindowTitleBarInactive = 221,
    WindowCloseInactive = 223,
    WindowCloseNormal = 224,
    WindowCloseHilited = 225,
    WindowCollapseInactive = 228,
    WindowCollapseNormal = 229,
    WindowCollapseHilited = 230,
    WindowZoomInactive = 233,
    WindowZoomNormal = 234,
    WindowZoomHilited = 235,
    WindowRightInactive = 238,
    WindowRightNormal = 239,
    GrowBoxActive = 243,
    GrowBoxInactive = 244,
}

impl Slot {
    pub fn index(self) -> usize {
        self as u16 as usize
    }
}
