//! Widget image slots of the appearance engine.
//!
//! Slot indices match the image table of Haxial `.hap` files (528 entries),
//! so imported appearances map 1:1 onto Sagrado widgets. Names follow the
//! AppearanceEdit documentation; index assignments were verified visually
//! against the images decoded from original appearances (WinXP, MacOS
//! Classic, BeOS). State order within a group is Normal, Hilited, Disabled —
//! window frames and controls use Normal, Focus, Hilited, Disabled. Only the
//! slots currently rendered by the engine are listed; unknown slots are
//! still imported and kept by index.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum Slot {
    PushButtonNormal = 25,
    PushButtonHilited = 26,
    PushButtonDisabled = 27,
    DefaultButtonNormal = 37,
    DefaultButtonHilited = 38,
    DefaultButtonDisabled = 39,
    IconButtonNormal = 49,
    IconButtonHilited = 50,
    IconButtonDisabled = 51,
    TickBlankNormal = 57,
    TickBlankHilited = 58,
    TickBlankDisabled = 59,
    TickTickedNormal = 61,
    TickTickedHilited = 62,
    TickTickedDisabled = 63,
    TickTristateNormal = 65,
    TickTristateHilited = 66,
    TickTristateDisabled = 67,
    MutexBlankNormal = 69,
    MutexBlankHilited = 70,
    MutexBlankDisabled = 71,
    MutexTickedNormal = 73,
    MutexTickedHilited = 74,
    MutexTickedDisabled = 75,
    MutexTristateNormal = 77,
    MutexTristateHilited = 78,
    MutexTristateDisabled = 79,
    PopupButtonNormal = 89,
    PopupButtonHilited = 90,
    PopupButtonDisabled = 91,
    PopupNoTitleNormal = 93,
    PopupNoTitleHilited = 94,
    PopupNoTitleDisabled = 95,
    PopupSymbolNormal = 97,
    PopupSymbolHilited = 98,
    PopupSymbolDisabled = 99,
    FocusBoxNormal = 101,
    FocusBoxHilited = 102,
    FocusBoxDisabled = 103,
    HorizSeparator = 105,
    VertSeparator = 106,
    Box = 107,
    FramedRaisedBox = 108,
    ProgressBar = 111,
    ProgressBarFill = 112,
    HSliderBarNormal = 126,
    HSliderBarHilited = 127,
    HSliderBarDisabled = 128,
    HSliderIndicatorNormal = 130,
    HSliderIndicatorHilited = 131,
    HSliderIndicatorDisabled = 132,
    HSliderPointedNormal = 134,
    HSliderPointedHilited = 135,
    HSliderPointedDisabled = 136,
    VSliderBarNormal = 138,
    VSliderBarHilited = 139,
    VSliderBarDisabled = 140,
    VSliderIndicatorNormal = 142,
    VSliderIndicatorHilited = 143,
    VSliderIndicatorDisabled = 144,
    VSliderPointedNormal = 146,
    VSliderPointedHilited = 147,
    VSliderPointedDisabled = 148,
    ColumnHeaderNormal = 150,
    ColumnHeaderHilited = 151,
    ColumnHeaderDisabled = 152,
    HScrollDoubleArrows = 162,
    HScrollSingleArrows = 163,
    HScrollDisabled = 164,
    HScrollTooSmall = 165,
    HScrollIndicatorNormal = 166,
    HScrollIndicatorHilited = 167,
    HScrollGripsNormal = 169,
    HScrollGripsHilited = 170,
    HScrollFirstLeftHilited = 172,
    HScrollFirstRightHilited = 173,
    HScrollSecondLeftHilited = 174,
    HScrollSecondRightHilited = 175,
    HScrollSingleLeftHilited = 176,
    HScrollSingleRightHilited = 177,
    VScrollDoubleArrows = 181,
    VScrollSingleArrows = 182,
    VScrollDisabled = 183,
    VScrollTooSmall = 184,
    VScrollIndicatorNormal = 185,
    VScrollIndicatorHilited = 186,
    VScrollGripsNormal = 188,
    VScrollGripsHilited = 189,
    VScrollFirstUpHilited = 191,
    VScrollFirstDownHilited = 192,
    VScrollSecondUpHilited = 193,
    VScrollSecondDownHilited = 194,
    VScrollSingleUpHilited = 195,
    VScrollSingleDownHilited = 196,
    MenuSeparator = 208,
    WindowFrameNormal = 220,
    WindowFrameFocus = 221,
    WindowCloseNormal = 223,
    WindowCloseFocus = 224,
    WindowCloseHilited = 225,
    WindowCloseDisabled = 226,
    WindowMinimizeNormal = 228,
    WindowMinimizeFocus = 229,
    WindowMinimizeHilited = 230,
    WindowMaximizeNormal = 233,
    WindowMaximizeFocus = 234,
    WindowMaximizeHilited = 235,
    WindowMaximizeDisabled = 236,
    WindowMenuNormal = 238,
    WindowMenuFocus = 239,
    WindowResizeNormal = 243,
    WindowResizeFocus = 244,
    PopupWindowFrameNormal = 248,
    PopupWindowFrameFocus = 249,
}

impl Slot {
    pub fn index(self) -> usize {
        self as u16 as usize
    }
}
